#!/usr/bin/perl
# a perl script which converts LaTeX/eepic/PSTricks pictures generated by jPicEdt, to PS/PDF files, by Søren Højsgaard, april 2006.

$numArgs = $#ARGV + 1;
my $mainfilename = $ARGV[0];

my $mainfilehead = $mainfilename;
$mainfilehead =~ s/\.tex//;
$mainfilename = $mainfilehead.".tex";

print "$mainfilehead\n";

my $outfilename = "$mainfilehead-wrap.tex";

open(OUT, "> $outfilename");

print OUT "
%% FILE AUTOMATICALLY GENERATED FROM $mainfilehead.tex\n
\\documentclass{article}
\\usepackage{isolatin1,pstricks}
\\begin{document}
\\pagestyle{empty} \n\n";

if ( !open( MAIN, $mainfilename ) )
{
    die( "error reading input file: $!" );
}

while( !eof( MAIN ) ) {
    my $line = <MAIN>;
    if ($line =~ /^\\begin{pspicture}/){
	print ("Line contains ...\n");
	print "$line\n";
	$line =~ /[^\(]+\(([^,]+),([^\)]+)\)\(([^,]+),([^\)]+)\)/;
	print "NO 1: $1 NO 2: $2 NO 3: $3 NO 4: $4\n";
	print OUT "$line" ;
	print OUT "\\rput($1,$2){\\tiny .}\n";
	print OUT "\\rput($3,$4){\\tiny .}\n";
    } else {   
	print OUT "$line" ;
    }
}

print OUT "\\end{document}\n";

close( IN );
close( OUT );

system "latex $outfilename";
system "dvips -E $mainfilehead-wrap -o $mainfilehead.eps";
system "epstopdf $mainfilehead.eps";
system "del $mainfilehead-wrap.log $mainfilehead-wrap.dvi $mainfilehead-wrap.aux";

# latex %1-wrap.tex
# dvips -E %1-wrap -o %1.eps
# epstopdf %1.eps
# del %1-wrap.log %1-wrap.dvi %1-wrap.aux


# \newenvironment{PSTmark}[4]{%
# \begin{pspicture}(#1,#2)(#3,#4)%
#     \rput(#1,#2){\tiny .}%
#     \rput(#3,#4){\tiny .}%
#     }%
# {\end{pspicture}}

