\documentclass{article}
\usepackage[svgnames]{xcolor}
\usepackage{pstricks}
\usepackage{siunitx}
\usepackage[tightpage,active]{preview}
\newcommand*\JPicIsIncluded{}
\pagestyle{empty}
\begin{document}
\begin{preview}
  \input{imagefile()}
\end{preview}
\end{document}
